/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Dashboard.module.css";

function AverageRatingByLocation() {
  return (
    <section className={styles.averageRatingByLocation}>
      <header className={styles.cardHeader}>
        <h2 className={styles.cardTitle}>Average Rating by Location</h2>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4dea6025980ee8492b10d857275386fd8203a18be03b547ed2d5a3783fb2fc1c?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
          alt=""
          className={styles.infoIcon}
        />
      </header>
      <div className={styles.ratingLegend}>
        <div className={styles.legendItem}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/177f863d1aabda939f3a25a42b85b878cfbe4be62b3e7964508405a4d4accb53?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
            alt=""
            className={styles.legendIcon}
          />
          <span>Positive</span>
        </div>
        <div className={styles.legendItem}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/693abf77d9a4ec3c65cffbcd6510be7c9ae382f9d65f1b308fb03d28d22457f4?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
            alt=""
            className={styles.legendIcon}
          />
          <span>Neutral</span>
        </div>
        <div className={styles.legendItem}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7a6fd5c16ddf1c627ac0ac576abc7bebc34599a202ca15a624e17f590333551e?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
            alt=""
            className={styles.legendIcon}
          />
          <span>Negative</span>
        </div>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bcd0f42cb853fe994b089440b43e5f18f2b21a3e13f233b9657488e955235943?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
        alt="Map showing average ratings by location"
        className={styles.ratingMap}
      />
    </section>
  );
}

export default AverageRatingByLocation;
