/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Dashboard.module.css";

function NavigationItem({ icon, label, active }) {
  return (
    <div className={`${styles.navigationItem} ${active ? styles.active : ""}`}>
      <img src={icon} alt="" className={styles.navigationIcon} />
      <span className={styles.navigationLabel}>{label}</span>
    </div>
  );
}

export default NavigationItem;
