/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Dashboard.module.css";

const topFoods = [
  { name: "Sandwich", reviews: 1000 },
  { name: "Sandwich", reviews: 1000 },
  { name: "Sandwich", reviews: 1000 },
  { name: "Sandwich", reviews: 1000 },
  { name: "Sandwich", reviews: 1000 },
];

function TopReviewedFood() {
  return (
    <section className={styles.topReviewedFood}>
      <header className={styles.cardHeader}>
        <h2 className={styles.cardTitle}>Top Reviewed Food</h2>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/61d8c3aef21a52c8de73e6c7dc298bcbcba379189011e5f7fbe51f65042be081?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
          alt=""
          className={styles.infoIcon}
        />
      </header>
      <ul className={styles.foodList}>
        {topFoods.map((food, index) => (
          <li key={index} className={styles.foodItem}>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d31441ab8664642af64cf0a202af7b421d6fd96678cb3f5bc3b2ee669962e004?placeholderIfAbsent=true&apiKey=556a066412f24cff924f0d1244f5cde7"
              alt=""
              className={styles.foodIcon}
            />
            <div className={styles.foodInfo}>
              <span className={styles.foodName}>{food.name}</span>
              <span className={styles.reviewCount}>{food.reviews} reviews</span>
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default TopReviewedFood;
